language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository ppa:kubuntu-ppa/backports -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake

before_script:
  - mkdir build
  - cd build
  - cmake .. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DASMJIT_BUILD_TEST=1 -DASMJIT_BUILD_SAMPLES=1

script:
  - make
  - ./asmjit_test
